require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# Override Firebase SDK Version
$FirebaseSDKVersion = '6.34.0'

target 'mstore' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  # Pods for mstore
  pod 'Google-Mobile-Ads-SDK', '~> 7.62.0'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

